# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0002_auto_20160901_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledchore',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='daily_modifier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='weekly_modifier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scheduledchore',
            name='day',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chore',
            name='frequency',
            field=models.CharField(max_length=30),
        ),
    ]
