# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0003_auto_20160902_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledchore',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledchore',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='daily_modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='weekly_modifier',
            field=models.IntegerField(default=0),
        ),
    ]
