# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0004_auto_20160902_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_picked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
